version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./docker/zookeeper/data:/var/lib/zookeeper/data
      - ./docker/zookeeper/log:/var/lib/zookeeper/log
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - ./docker/kafka/data:/var/lib/kafka/data
    networks: 
      - kafka-network

  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.0.0
    container_name: kafkarest
    depends_on:
      - kafka
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_HOST_NAME: kafkarest
      KAFKA_REST_LISTENERS: http://kafkarest:8082
    networks: 
      - kafka-network

  kafka-topic-ui:
    image: landoop/kafka-topics-ui:0.9.4
    depends_on:
      - kafka-rest
    environment:
      KAFKA_REST_PROXY_URL: http://kafkarest:8082
      PROXY: "true"
    ports:
      - "8000:8000"
    networks: 
      - kafka-network

networks: 
  kafka-network:
